# 1. INTRODUCTION

Resource management is characterized by trade-offs between conservation- and utilization-based objectives. Fisheries managers, for example, are tasked with ensuring that populations remain sufficiently abundant to minimize extinction risk and sustain intact ecosystems. While conservation objectives are often legally prioritized, managers are simultaneously under pressure to meet harvest objectives related to food security, cultural traditions, or economic development. To reconcile these tensions, fisheries scientists have attempted to design harvest strategies that account for trade-offs between harvest and conservation while remaining robust to uncertainty [@Punt2016].

Many fisheries are multi-stock, composed of reproductively isolated populations that differ in productivity, capacity, and sustainable exploitation rates [@Ricker1973; @Hilborn1985]. The simplest management approach, and historically the most frequently employed, is to identify target harvest rates based on the dynamics of stock aggregates defined by management boundaries rather than underlying population structure [@Stephenson2002a]. If the dynamics of stocks within the fishery are similar, or exploitation is low, such a strategy may be effective. When these assumptions are not met, however, harvest rates that are sustainable at the aggregate scale may deplete less productive stocks and result in extirpation [@Ricker1973; @Reiss2009]. 

Reductions in among stock diversity can negatively impact conservation and harvest objectives. Individual stocks often exhibit unique phenotypes or responses to local environmental conditions, resulting in asynchronous dynamics that increase the stability of the aggregate as a whole--a process referred to as the portfolio effect [@Hilborn2003; @Schindler2010]. As stock diversity declines, however, portfolio effects may weaken, increasing the spatial and temporal variability of catches [@Satterthwaite2015; @Freshwater2019] and reducing long-term resilience to future climate change [@Anderson2015]. Ultimately, minimizing harvest of depleted stocks in mixed-stock fisheries may be necessary to maintain diversity. One strategy is to implement highly precautionary management targets for ecological aggregates that are based on the dynamics of the least productive stock(s). While such actions will reduce the probability of overfishing across all stocks, it is likely to increase tension between conservation and socio-economic objectives as yield is lost from productive stocks. In cases where declines in landings have already strained fishing communities, further reductions may receive substantial political opposition.

An alternative method of reconciling conservation and socio-economic objectives is to shift harvest effort towards single-stock fisheries, which allow managers to reduce the risk of overexploitation of less productive stocks while capitalizing on the surplus production of other stocks. Increasing stock selectivity (i.e. the ability to target specific stocks) is particularly relevant to Pacific salmon (*Oncorhynchus* spp.) where stocks are highly structured, but most harvest occurs in mixed-stock fisheries [@DFO2017a]. Salmon management aggregates often include stocks that vary in status and, in extreme cases, can include stocks that sustain large commercial fisheries as well as stocks of critical conservation concern. 

Extensive efforts have been made to fine-tune commercially important salmon fisheries to maximize their stock selectivity. Variation among stocks in migratory routes or timing are incorporated into run reconstructions, which generate stock-specific harvest rates and, ultimately, time series of stock-specific recruit abundance [@Cunningham2018]. Given sufficient spatial or temporal segregation among stocks, managers can utilize these data to reduce fishing mortality on depleted stocks [@Walters2008; @Cunningham2019]. In other cases, however, the overlap among stocks is too great for closures to be effective. In such instances, stock selectivity could be increased by developing terminal fisheries close to spawning grounds [@Walters2008]. 

Fraser River sockeye salmon (*Oncorhynchus nerka*) sustain a particularly complex mixed-stock fishery. The aggregate is Canada’s largest sockeye salmon run, but productivity throughout the system declined in the 1990s [@Peterman2012; @Freshwater2018], resulting in frequent fishery closures and an emergency federal inquiry. Recently, ten of 24 stocks were assessed as at risk of extinction [@COSEWIC2017]. Although status is assessed at the stock level, harvest in the Fraser River aggregate is managed using four run timing groups (management units; MUs). Thus harvest effort can currently be constrained at the MU-, but not the stock-specific, scale. As a result, abundant and endangered stocks are harvested in the same mixed-stock fishery (e.g. Chilko and Quesnel stocks, respectively, in the summer-run MU [-@COSEWIC2017]). 

As knowledge of population structure improves, it will be possible to more broadly utilize management levers that adjust fishery stock-selectivity. There is growing interest in developing single-stock fisheries in terminal areas to increase economic benefits and reduce extirpation risk (e.g. Taylor and Dickie [-@Taylor2009]). While the challenges associated with mixed-stock salmon fisheries have been widely documented [@Ricker1973; @Hilborn1985; @Walters2019], analyses focused on sustaining less productive stocks typically seek to identify mixed-stock exploitation rates that are sufficiently conservative to avoid extirpation [@Hawkshaw2015]. To explicitly test whether shifting harvest from mixed- to single-stock fisheries results in improved outcomes requires fishery-specific harvest control rules that are less commonly implemented in simulation models. 

Additionally, tradeoffs between mixed- and single-stock fisheries should be evaluated in the context of ecological processes that may limit recovery, even if they are beyond the control of managers. For example, widespread, synchronous declines in productivity [@Peterman2012; @Freshwater2018] may reduce abundance across all stocks to such an extent that even highly selective fisheries do not result in improved performance. Single-stock fisheries will also be disproportionately impacted by natural mortality during freshwater migrations. En route mortality increases when fish passage is obstructed (e.g. 2019 Big Bar slide) or river temperatures are high, can exceed 90% in certain years [@Cooke2004], and is likely to be more severe as climate change impacts accelerate [@Martins2012].

Here we use stochastic closed-loop simulations to evaluate whether increasing stock selectivity, by shifting harvest from mixed- to single-stock fisheries, is likely to improve management outcomes for Fraser River sockeye salmon. We first develop abundance-based harvest control rules for mixed- and single-stock fisheries that could be implemented using commonly available data. We then evaluate how changing allocations to each fishery will affect conservation- and harvest-based performance metrics. Finally, we quantify how the relative performance of mixed- and single-stock fisheries could be moderated by two ecological processes: population productivity and en route mortality. 