# 4. Discussion

Shifting harvest from mixed- to single-stock fisheries may provide a means of maximizing harvest opportunities on abundant stocks while minimizing risks to sympatric stocks of concern. While increasing stock selectivity has intuitive conservation benefits for fisheries [@Walters2008; @Taylor2009], the trade-offs among harvest and conservation objectives of such a transition are rarely quantified. Using a stochastic, closed-loop simulation model, we found that increasing allocations to single-stock fisheries resulted in improved conservation performance, albeit at the cost of reduced catches. However, we also determined that trade-offs between objectives were sensitive to the ecological scale of performance metrics, the structure of each fishery's harvest control rule, and the population dynamics of individual stocks within the aggregate.

At the aggregate scale, fully single-stock fisheries maximized return abundance and the proportion of stocks above conservation benchmarks, while fully mixed-stock fisheries resulted in reduced conservation performance, as well as reductions in long-term catches and catch stability due to recruitment overfishing. Intermediate allocations that split total allowable catch between mixed- and single-stock fisheries relatively equally maximized catch metrics without substantial declines in conservation performance. These results were driven by multiple factors. First, single-stock fisheries were restricted when the target stock was below its biological benchmark, resulting in more conservative fisheries and a negative relationship between single-stock allocations and total exploitation rate. Second, even though the mixed-stock harvest control rule aimed to maintain aggregate exploitation rates at or below the level associated with maximum sustainable yield, it failed to account for differences among stocks in productivity, which reduce sustainable exploitation rates [@Ricker1973]. Thus fully mixed-stock fisheries overharvested less productive populations, reducing both conservation performance and long-term yields. Third, the mixed-stock harvest control rule's reference points assumed that aggregate population dynamics were stationary and did not account for recent declines in productivity [@Peterman2012; @Freshwater2018]. Although single-stock fisheries did not explicitly address changes in productivity, they were capable of responding to years of low stock-specific spawner abundance.

The impacts of single-stock fisheries were not homogeneous, but varied among stocks due to differences in intrinsic productivity and carrying capacity. While the conservation performance of smaller, less productive stocks improved as single-stock allocations increased, more productive or abundant stocks exhibited mixed responses. The Harrison stock's abundance regularly exceeded the conservation benchmark necessary to allow single-stock harvest to occur. Hence realized exploitation rates, as well as catch and conservation performance, were largely independent of fishery allocation. Conversely, the Chilko stock was negatively impacted by increasing single-stock fishery allocations because intermittent closures resulted in years where escapement exceeded capacity, triggering declines in abundance and catch (we note that escapements exceeding capacity may provide important ecosystem services not internalized here, e.g. nutrient subsidies to terrestrial systems [@Helfield2001]). Differences in stock-specific yield across various management procedures may be driven by productivity and capacity, as modeled here, or by mixed-stock fishery selectivity [@Walters2008]. Regardless of mechanism, these divergent responses among stocks suggest stock-specific trade-offs should be considered when evaluating the benefits of changing fishery allocations.

The association between population parameters and relative performance of each fishery illustrates an important characteristic of closed-loop simulation models--namely, that their conclusions are dependent on the underlying stock-recruit model [@Punt2016], which cannot be "known" with certainty. For example, if the Chilko stock were simulated with an alternative model that did not include overcompensation (e.g. Beverton-Holt), then the performance of the single-stock fishery would likely have improved. While we recognize that incorporating only a single stock-recruit relationship in this analysis ignores one dimension of uncertainty, we believe that our choice was justified given expert consensus that Ricker/Larkin models best describe Fraser River sockeye salmon dynamics (demonstrated by their use in previous Fraser River stock assessments [@DFO2018c]).

Various single-stock fishery frameworks could be implemented, including those that supplement catch through additional harvest in terminal areas [@DFO2017a], effectively attempting to fish each stock at close to its maximum sustainable yield. Yet such strategies are relatively "data-hungry", requiring stock-specific in-season estimates of terminal abundance and fishery reference points that are often lacking [@Price2008; @Holt2015], and may only produce marginal gains in long-term yield [@Walters2008]. Instead our goal was to implement a relatively simple and conservative single-stock harvest control rule that could increase the probability of maintaining stock diversity with small additional requirements in management capacity. In this case, the decision to open a particular stock's fishery could be made prior to the start of the fishing season based on recent abundance relative to benchmarks (here derived from stock-recruit parameters, but if those are lacking, average spawner abundance could be used). This strategy attempts to address stock diversity goals [@DFO2005], without being overly constrained by data limitations.

Improvements in conservation performance as single-stock allocations increase will be sensitive to the underlying harvest control rules within each fishery. For example, mixed-stock Fraser River sockeye salmon fisheries are currently managed with a total allowable mortality rule--a framework that includes a range of precautionary adjustments, as well as a maximum exploitation rate (60%) that is below estimates of $u_{msy}$ for most stocks [@Pestal2011]. When we simulated an equivalent rule, mixed-stock fisheries had no evidence of recruitment overfishing and moderate declines in conservation performance relative to single-stock fishery management procedures. Thus there may be little benefit to developing single-stock fisheries if mixed-stock fisheries include sufficiently precautionary reference points. Since such reference points often depend on relatively precise estimates of stock-recruit parameters and collaborative multi-year modeling efforts [@Pestal2011], single-stock strategies may be most effective when stock status within an aggregate is variable and management resources are limited.

The performance of single-stock fisheries will also depend on ecological processes outside of fisheries managers' control. For example, when productivity is uniformly low, the performance of mixed- and single-stock fisheries converged because neither fishery was regularly opened. As a result, a transition to single-stock fisheries is unlikely to counteract declines in salmon abundance driven by widespread, synchronous declines in marine survival [@Peterman2012]. In fact, increasing covariance among stocks may result in modest improvements in the performance of mixed-stock harvest control rules as aggregates increasingly behave like single populations [@Freshwater2019].

Options to increase stock selectivity are limited when a salmon aggregate contains populations that share similar migration phenologies [@Walters2008]. In such a situation developing single-stock fisheries likely requires moving harvest to terminal areas and additional management considerations. First, adult fish will recruit into terminal fisheries only after completing their freshwater migrations. En route mortality rates can exceed 90% in certain years [@Cooke2004] and high mortality events are likely to increase due to climate change impacts [@Martins2011]. Thus terminal single-stock fisheries will have access to less harvestable biomass than downstream fisheries, resulting in smaller landings at a given harvest rate. Second, a larger number of fisheries within each aggregate will require additional management and enforcement capacity that may be particularly costly in remote areas. While in-season estimates of stock-specific abundance are available for Fraser River sockeye salmon, they are not for many other aggregates, which may increase outcome uncertainty and the risk of overharvest in single-stock fisheries. Third, from a socio-economic perspective, the landed value per weight of terminal catches will be lower than marine caught fish, leading to reduced commercial opportunity, because salmon expend large portions of their energy reserves while migrating [@Taylor2009]. Finally, increasing single-stock harvest will result in fundamental changes in access among user groups. Such changes will clearly result in socio-economic trade-offs, but may also more directly impact fisheries managers through, for example, changes in gear type and selectivity. Ideally a full management strategy evaluation could be used to specify conservation and socio-economic objectives of all stakeholders, then quantify trade-offs prior to changes in allocation. 

## Acknowledgements

This work would not have been possible without the efforts of the many biologists and technicians who collected the Fraser River sockeye salmon catch and escapement data. We are grateful to Brendan Connors, Micahel Folkes, James Robinson, and Travis Tai for helpful advice. We also thank Catarina Wor for valuable feedback on an earlier draft of the manuscript, Catherine Michielsens for assistance implementing recursive Bayes stock recruit models, and two anonymous reviewers, whose comments greatly improved this manuscript's quality. This project was supported by Fisheries and Oceans Canada through the Strategic Program for Ecosystem-based Research and Advice (SPERA).

## Appendix A. Supplementary methods

Additional details on the simulation model's operating model and management procedure are available in the online version.

## Appendix B. Sensitivity analyses

Analyses to evaluate the impact of temporal autocorrelation, observation error, outcome uncertainty, and interannual variation in stochastic parameters on our conclusions are available in the online version.
