---
title: "Benefits and limitations of increasing the stock-selectivity of Pacific salmon fisheries"
author: |
  First. M. Last^1^ and
  Alex B. Smith^2^
author_list: "Last, F.M. and Smith, A.B."
address: |
  ^1^Pacific Biological Station\
     Fisheries and Oceans Canada, 3190 Hammond Bay Road\
     Nanaimo, British Columbia, V9T 6N7, Canada\
  ^2^Far, far away\
     Another Galaxy
month: Month # fill in
year: 2019
report_number: nnn
region: Pacific Region
citation_other_language: "Last, F.M. et Smith, A.B. Title Here (*Latin Species Name*). DFO Secr. can. de consult. sci. du MPO. Doc. de rech 2019/nnn. iv + 13 p."
abstract: |
 Population diversity can stabilize ecological dynamics and increase resilience to future environmental change. In exploited systems, however, management goals to preserve diversity may be in tension with harvest objectives. For example, fisheries managers may forgo opportunities to sustainably harvest abundant populations to reduce risks to less productive populations. Increasing the stock selectivity of fisheries is one management lever that may allow for both conservation- and catch-based objectives to be met. We developed a model that simulates the dynamics of a Pacific salmon stock aggregate and its fishery to evaluate how changing allocations between mixed- and single-stock fisheries influences management performance. We focused on relatively generic management strategies that may be implemented in a range of salmon fisheries. Additionally we examined how the relative performance of mixed- and single-stock fisheries may change under alternative ecological and management scenarios. We found that increasing single-stock fishery allocations increased aggregate abundance and improved the status of some stocks relative to their conservation benchmarks. However these improvements did not occur uniformly--relatively abundant, productive stocks exhibited no change, or even declines, in conservation performance as single-stock fishery allocations increased. Furthermore, differences in performance between mixed- and single-stock fisheries were reduced when productivity was uniformly low, when the mixed-stock fishery was managed conservatively, or when mortality during freshwater migrations was high. While single-stock fisheries can increase the probability that conservation-based objectives will be met, they are not a panacea and may only be effective when specific conditions are met.
header: "Draft working paper --- Do not cite or circulate" # or "" to omit
output:
 # csasdown::resdoc_pdf:
 #   french: false
  csasdown::resdoc_word
# ------------
# End of options to set
knit: bookdown::render_book
link-citations: true
bibliography: bib/ms_singleStock.bib
csl: csl/conservation-biology.csl # or csl/csas-french.csl for French
# Any extra LaTeX code for the header:
# header-includes:
# - \usepackage{tikz}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
# adjust as desired:
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = if (knitr:::is_latex_output()) "knitr-figs-pdf/" else "knitr-figs-docx/",
  cache.path = if (knitr:::is_latex_output()) "knitr-cache-tex/" else "knitr-cache-docx/",
  fig.asp = 0.618,
  fig.width = 9,
  out.width = "6in",
  echo = FALSE,
#  autodep = TRUE,
#  cache = TRUE,
  cache.comments = FALSE,
  dev = if (knitr:::is_latex_output()) "png" else "pdf",
  dpi = 180,
  fig.align = "center",
  fig.pos = "htb"
)
options(kableExtra.latex.load_packages = FALSE)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(csasdown)
library(here)
library(tidyverse)
library(samSim)
library(knitr)
library(kableExtra)
```
