---
header-includes:
  - \usepackage{caption}
output:
  word_document:
    fig_caption: yes
    reference_docx: templates/blankMS.docx
  # bookdown::pdf_document2:
  #   fig_caption: yes
  #   latex_engine: pdflatex
    # includes:
    #   in_header: preamble-latex.tex
csl: csl/ecology.csl
link-citations: no
bibliography: bib/ms_singleStock.bib
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
# adjust as desired:
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = if (knitr:::is_latex_output()) "knitr-figs-pdf/" else "knitr-figs-docx/",
  cache.path = if (knitr:::is_latex_output()) "knitr-cache-tex/" else "knitr-cache-docx/",
  fig.asp = 0.618,
  fig.width = 9,
  out.width = "6in",
  echo = FALSE,
#  autodep = TRUE,
#  cache = TRUE,
  cache.comments = FALSE,
  dev = if (knitr:::is_latex_output()) "png" else "png",
  dpi = 180,
  fig.align = "center",
  fig.pos = "htb"
)
options(kableExtra.latex.load_packages = FALSE)
```

```{r loadSimRunData, include=FALSE}
library(samSim)
library(ggpubr)
library(tidyverse)
## Simulation ran in varyAllocation_mainSimRun.R, which also includes example figures
simPar <- read.csv(here::here("data", "manProcScenarios",
                        "fraserMPInputs_varyAllocationVaryMixHCR.csv"),
                   stringsAsFactors = F)
simParTrim <- simPar %>%
  filter(nameOM %in% c("ref", "enRoute"),
         benchmark == "stockRecruit")
scenNames <- unique(simParTrim$scenario)
dirNames <- sapply(scenNames, function(x) paste(x, unique(simParTrim$species), 
                                                sep = "_"))

#ID stocks included in CU-specific analyses
cuPar <- read.csv(here::here("data/fraserCUPars.csv"), stringsAsFactors = F)
summCUs <- cuPar %>% 
  filter(manUnit == "Summ") %>% 
  mutate(abbStkName = abbreviate(stkName, minlength = 4)) %>% 
  select(abbStkName) %>% 
  unlist()

agVarsToPlot <-  c("medRecRY", "medSpawners", "ppnCULower", 
                   "medCatch", "stabilityCatch", "medER")

agDat <- buildDataAgg(dirNames, agVars =  agVarsToPlot, 
                      keyVarName = "ppnMixed") %>%
  mutate(mp = case_when(
    str_detect(mp, "genPA") ~ "Generic",
    str_detect(mp, "TAM") ~ "TAM"
  ), 
  labelledVar = var) %>%
  mutate(mp = as.factor(mp), 
         labelledVar = fct_recode(labelledVar, 
                                  "Aggregate\nReturn Abundance" = "medRecRY",
                                  "Aggregate\nSpawner Abundance" = 
                                    "medSpawners",
                                  "Proportion of CUs\nAbove Cons. BM" = 
                                    "ppnCULower",
                                  "Aggregate\nCatch" = "medCatch",
                                  "Catch\nStability" = "stabilityCatch",
                                  "Median\nExploitation Rate" = "medER")) 

refDat <- agDat %>% 
  filter(om == "ref", 
         mp == "Generic") 
```

```{r aggDot, warnings=FALSE, messages=FALSE, fig.cap="Figure S2.1 Changes in aggregate conservation- and catch-based performance metrics across a range of fishery allocations, i.e. range of proportional allocation of mixed- to single-stock where 1 and 0 are fully mixed- and fully single-stock fisheries, respectively. Points represent medians and whiskers represent 90th percentile intervals among Monte Carlo trials. Abundance and catch are in millions of fish."}
# color figures not supported by Conservation Biology
# colPal <- viridis::viridis(length(levels(refDat$ppnMixed)), begin = 0, 
#                            end = 1, option = "plasma")
colPal <- grDevices::gray.colors(n = length(levels(refDat$ppnMixed)), 
                                 start = 0.9, end = 0.1)
names(colPal) <- levels(refDat$ppnMixed)

panelLabs <- data.frame(lab = c("a)", "b)", "c)", "d)", "e)", "f)"),
                        var = factor(agVarsToPlot, 
                                     levels = unique(agVarsToPlot)))

agDotPlotList <- lapply(seq_along(agVarsToPlot), function(x) {
  dum <- refDat %>% 
    filter(var == agVarsToPlot[x])
  p <- ggplot(dum, aes(x = ppnMixed, y = avg, ymin = lowQ, ymax = highQ,
                          fill = ppnMixed)) +
    ylim(0.85 * min(dum$lowQ), max(dum$highQ)) +
    labs(x = "", y = unique(dum$labelledVar)) +
    geom_pointrange(shape = 21, fatten = 2.5, size = 2,
                    position = position_dodge(width = 0.65)) +
    geom_text(data = panelLabs %>% filter(var == agVarsToPlot[x]),
              mapping = aes(x = 0.9, y = min(0.85 * dum$lowQ), label = lab,
                            vjust = 0),
              show.legend = FALSE, inherit.aes = FALSE, size = 5) +
    scale_fill_manual(guide = FALSE, values = colPal)
  if (unique(dum$var) %in% c("medRecRY", "medSpawners", "ppnCULower")) {
    p <- p +
      theme_sleekX(position = "top", axisSize = 15)
  } else {
    p <- p +
      theme_sleekX(position = "bottom", axisSize = 15)
  }
  return(p)
})

panelFig <- ggarrange(agDotPlotList[[1]], agDotPlotList[[2]],
                              agDotPlotList[[3]],
                  agDotPlotList[[4]], agDotPlotList[[5]], agDotPlotList[[6]],
                  ncol = 3, nrow = 2, align = "v", heights = c(0.85, 1.1))
annotate_figure(panelFig, bottom = text_grob("Proportion Mixed-Stock TAC",
                                             size = 17, vjust = -1))
```